Redesign registry; Allow publishing to registry
nushell/nupm pull request #86
Opened 2024-03-26 17:02 UTC by kubouch

## Description

This changes registry to from *one* file that is *manually updated* to *multiple* files that are *auto-generated*.

### Multiple files
Registry is now a .nuon file which contains a table of one file per package (called "package files", not sure how to call them). See the `registry/` and `tests/packages/registry/` directories as examples.

### Auto-generated
The registry is now expected to be auto-generated via the new `nupm publish` command. The intended workflow is:
1. Check out the repository with the registry
2. Run `nupm publish /path/to/checked/out/registry.nuon ...` to preview changes
3. Run `nupm publish /path/to/checked/out/registry.nuon ... --save` to write the changes to the registry/package files
4. Commit the changes to the registry and create a PR

The main registry file is sorted by name. The "package file" is sorted by version. Both sortings are done by `nupm publish`.

### Misc changes

* The structure of the registry is also different. The git/local package type is now encoded in a flat table instead of being a separate record. See `registry/` and `tests/packages/registry/` for examples.
* The `path` field can be `null`, not requiring the "."

### TODO

- [ ]: Add package file hashing to stop redownloading them all the time

2024-04-06 09:40 UTC, amtoine requested changes
just a few remarks but, otherwise, all looks pretty cool.
it's not easy to test right now because the new registry URL is invalid until we land that PR...



## the registry files
i've been able to make sure all the registry files were valid, which is very nice.
below is the script that passes :ok_hand:
```nushell
use std assert

def make-it-similar []: table<name: string, version: string, url: string, revision: string, path: string> -> table<name: string, version: string, url: string, revision: string, path: string> {
    sort-by version name | select name version url revision path
}

let old = http get https://raw.githubusercontent.com/nushell/nupm/main/registry.nuon
    | get git
    | make-it-similar

let new = open registry/registry.nuon
    | get path
    | each {|it| open ("registry/" | path join $it)} # open each registry package file
    | flatten                  # extract the path and revision from `$.info`
    | update info { flatten }  # |
    | flatten --all            # |
    | reject type
    | default "." path         # remove the `null`
    | make-it-similar

assert equal $new $old
print "all good"
```

2024-04-06 09:40 UTC, amtoine commented on registry/registry.nuon
a comment for all the registry NUON files: would it be better to have them not on a single line? i guess having them in a pretty format, e.g. with `to nuon -i 4` would allow easier debugging and seeing what changed from one revision to another?

i mean, this is not critical, it's always possible to keep that compact format and use `open`, `to nuon -i` and things like `diff -u` to see the "_real_" diff between the NUON data :wink:

2024-04-06 09:40 UTC, amtoine commented on toolkit.nu
> +    }
might be able to write a simpler
```nushell
print $"PATH: ($env.PATH? | default $env.Path? | default [])"
```
but this `if` is fine, as you want :+1:

2024-04-06 09:40 UTC, amtoine commented on tests/mod.nu
> +            nupm publish $tmp_reg_file --local --save --path $'../($pkg)'
would the following be more robust on Windows? (yeah i'm always worried about Windows lol)
```suggestion
            nupm publish $tmp_reg_file --local --save --path (".." | path join $pkg)
```

2024-04-06 09:40 UTC, amtoine commented on tests/mod.nu
> +        # cp -r tests/packages $env.NUPM_TEMP
```suggestion
```

2024-04-10 20:54 UTC, amtoine commented
windows being painful again...

2024-04-10 21:27 UTC, kubouch commented on registry/registry.nuon
It takes way too much space with `-i 4`, but being able to diff properly is nice... You can also use a better diff tool like difftastic, but it's still quite hard to see.

I'm kind of leaning towards keeping it as-is because it's meant to be processed by machines only. Maybe we can roll with it for a while and see if it becomes a pain to debug and switch to `-i 4` if so?

2024-04-10 21:29 UTC, kubouch commented
The hash is failing. I'm wondering if it's Windows vs. Unix newlines.

2024-04-12 16:14 UTC, amtoine commented on registry/registry.nuon
yup, we can definitely do that!

2024-04-15 21:01 UTC, kubouch commented
Related to diffing the nuon files, inspired by https://www.youtube.com/watch?v=Md44rcw13k4. Pasting it here from Discord so it won't get burried:
* create a new file called .gitattributes
* put the following like in it `*.nuon diff=nuon`
* run the following command `git config diff.nuon.textconv nu`
* modify a NUON file and see how the diff is pretty

2024-05-04 12:28 UTC, kubouch commented
@amtoine I fixed the Windows issue! It wasn't newlines but the --path flag which was constructed with `\` on Windows and `/` on Mac/Linux. I forced it to always have `/`. Feel free to approve and merge!

2024-05-04 12:37 UTC, kubouch commented
One argument for keeping the nuon files "raw" is that they do not contain newlines, so their hashes should be the same on Windows/non-Windows. If we made the nuon files more human-friendly, they would contain newlines which could potentially mess things up: Simply opening and closing a nuon file could change the line endings in the entire file, making its hash not match the expected hash. Maybe it would be fine, but we'd have to make sure and test it, I'd rather avoid this by having no newlines, at least for now.

2024-05-04 15:37 UTC, texastoland commented
Just devil's advocate but could you manually replace all `\r` with empty string before saving?

2024-05-04 18:22 UTC, kubouch commented
> Just devil's advocate but could you manually replace all `\r` with empty string before saving?

Yes, that's an option (or convert all `\n` to `\r\n`). I chose to side step it entirely for now. I'm a bit afraid that once we start messing with newlines, we'd open a can of works. Like I mentioned above, I can imagine just viewing the file in some smart editor could convert the line endings automatically. Then there is also Git which can convert the line endings depending on user's preferences. It's not something I want to mess with right now 😆 .

2024-05-05 11:09 UTC, amtoine commented
nice job @kubouch !!

Windows is such a pain...
in `nu-git-manager`, i wrote a `path sanitize` command that makes Windows path better (lol) and i have to use it almost on all paths :rofl:

2024-05-05 11:17 UTC, amtoine requested changes
the new commits look fine to me :ok_hand: 

there's just a review question and some missing packages :wink: 
```nushell
use std assert

def make-it-similar []: table<name: string, version: string, url: string, revision: string, path: string> -> table<name: string, version: string, url: string, revision: string, path: string> {
    sort-by version name | select name version url revision path
}

let old = http get https://raw.githubusercontent.com/nushell/nupm/main/registry.nuon
    | get git
    | make-it-similar

let new = open registry/registry.nuon
    | get path
    | each {|it| open ("registry/" | path join $it)} # open each registry package file
    | flatten                  # extract the path and revision from `$.info`
    | update info { flatten }  # |
    | flatten --all            # |
    | reject type
    | default "." path         # remove the `null`
    | make-it-similar

if $new != $old {
    $new | to nuon --indent 4 | save --force /tmp/new.nuon
    $old | to nuon --indent 4 | save --force /tmp/old.nuon
    diff -u /tmp/old.nuon /tmp/new.nuon
}
print "all good"
```
gives me
```diff
--- /tmp/old.nuon       2024-05-05 13:15:41.093046938 +0200
+++ /tmp/new.nuon       2024-05-05 13:15:41.093046938 +0200
@@ -245,55 +245,6 @@
         .
     ],
     [
-        nu_plugin_explore,
-        "0.92.0",
-        "https://github.com/amtoine/nu_plugin_explore",
-        "0.92.",
-        .
-    ],
-    [
-        nu_plugin_clipboard,
-        "0.92.1",
-        "https://github.com/FMotalleb/nu_plugin_clipboard",
-        "98d7102",
-        .
-    ],
-    [
-        nu_plugin_explore,
-        "0.92.3-2595f31541554c6d8602ebebc9dffbc4dd29dd89",
-        "https://github.com/amtoine/nu_plugin_explore",
-        "0.92.3-2595f31541554c6d8602ebebc9dffbc4dd29dd89",
-        .
-    ],
-    [
-        nu_plugin_explore,
-        "0.92.3-55edef5ddaf3d3d55290863446c2dd50c012e9bc",
-        "https://github.com/amtoine/nu_plugin_explore",
-        "0.92.3-55edef5ddaf3d3d55290863446c2dd50c012e9bc",
-        .
-    ],
-    [
-        nu_plugin_explore,
-        "0.92.3-be5ed3290cb116cbe9f3038f7a2d46aaac85a25c",
-        "https://github.com/amtoine/nu_plugin_explore",
-        "0.92.3-be5ed3290cb116cbe9f3038f7a2d46aaac85a25c",
-        .
-    ],
-    [
-        nu_plugin_explore,
-        "0.92.3-c06ef201b72b3cbe901820417106b7d65c6f01e1",
-        "https://github.com/amtoine/nu_plugin_explore",
-        "0.92.3-c06ef201b72b3cbe901820417106b7d65c6f01e1",
-        .
-    ],
-    [
-        nu_plugin_explore,
-        "0.93.0",
-        "https://github.com/amtoine/nu_plugin_explore",
-        "0.93.0",
-        .
-    ],
-    [
         nu_plugin_port_scan,
         "1.0.10",
         "https://github.com/FMotalleb/nu_plugin_port_scan",
```
related to
- #87 
- #88

2024-05-05 11:17 UTC, amtoine commented on nupm/publish.nu
> +    let path = if $path != null { $path | str replace '\' '/' }
shouldn't all `\` be replaced by `/`?
```suggestion
    let path = if $path != null { $path | str replace --all '\' '/' }
```

2024-05-05 12:35 UTC, kubouch commented on nupm/publish.nu
> +    let path = if $path != null { $path | str replace '\' '/' }
Yes, you're right, I forgot about that.

2024-05-05 12:44 UTC, kubouch commented
Ah yeah, it's missing the added packages. I currently don't have time to add them. If you have time, you can merge it and publish them again to the registry using the new `nupm publish`. This way it would get tested by someone apart from me. Otherwise, I can do it whenever I find the time.

2024-05-08 21:16 UTC, kubouch commented
Now thinking about it, I think we should support only semver-style versions because we need to be able to sort by version and select the latest. The same with the `main` version. At least in the official registry, having random strings would be too confusing. I understand the value of having, e.g., the `main` as an always up-to-date package, but it really messes up the version resolution.

I'd propose keeping only semver in the official registry, but let's keep experimenting with being able to have some alternative versions.

2024-05-08 21:21 UTC, texastoland commented
> I think we should support only semver-style versions

Commit hashes are [supported in semver](https://semver.org/#spec-item-10) (in case it helps).

2024-05-08 21:52 UTC, kubouch commented
TIL, but I still think we need to restrict our versions to a subset that doesn't prevent sorting. Otherwise, we wouldn't be able to reliably update a package. You want to type `nupm update nu_plugin_explore` and get the latest version. Now, which one of the four different `0.92.3`s is the newest?

We could support having a `null`/`main`/`latest` in place of the version. In that case, this version would always be considered “newest” and would be always re-fetched when you call `nupm update`. `nupm install` would also always install this version if you don't specify the version manually. This would be useful for cases like the current `tmux-sessionizer` tracking the main branch. That would be OK for a private / unofficial registry. For the official registry, we'd disallow it.

2024-05-08 22:40 UTC, texastoland commented
> I still think we need to restrict our versions to a subset that doesn't prevent sorting.

I trust your vision for it ✌🏼 FWIW the spec is `major.minor.patch-alphabetical+ignored`.

2024-05-10 07:21 UTC, amtoine commented
i agree @kubouch, maybe these deps are simply ill-defined :eyes: 

does that mean that
- the two i cannot add shouldn't be added?
- the ones that are not proper semver should be removed?

then we can land this PR :pray:

2024-05-25 20:25 UTC, kubouch commented
@amtoine I republished the problematic packages, should be good now. The problem with nu_plugin_explore is that revisions up to 0.93.0 still had the old version 0.1.2 in their nupm.nu, so they're not publishable because 0.1.2 is already published. Seems like you forgot to update it.

2024-06-01 10:47 UTC, amtoine commented
aaah yeah, you're right :sob: 

we're good to land then? i kinda lost track of whole the changes lol

2024-06-01 10:47 UTC, amtoine commented
still think the registry diffs are impossible to review, which is a bit of a bummer imo :confused:

2024-06-02 03:26 UTC, texastoland commented
Same. I think there'd be some value in standardizing on Unix line endings. Otherwise DX will be a step above binary. Epic regardless 👏🏼

2024-06-03 19:44 UTC, kubouch commented
Thinking about it, I think what we can do is to make `nupm publish` generate one type of line ending (LF or CRLF), but more importantly, we can change the hash function to replace all CRLF with LF in text files and hash that. That should give us identical hashes on Windows and Unix.

I'm going to merge this as-is, but I'll play with the newlines in the next PR, or anyone else can take a shot at it. I think relying forever on having zero newlines doesn't sound very robust in the long run.

2024-06-03 19:45 UTC, merged